"""empty message

Revision ID: 0fa2468ff35c
Revises: 
Create Date: 2019-09-15 09:48:01.280028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa2468ff35c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserData',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Level', sa.String(length=256), nullable=True),
    sa.Column('Name', sa.String(length=256), nullable=True),
    sa.Column('Phone', sa.String(length=256), nullable=True),
    sa.Column('Time', sa.String(length=256), nullable=True),
    sa.Column('Description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserData')
    # ### end Alembic commands ###
