"""empty message

Revision ID: 891f71f857c2
Revises: 
Create Date: 2019-09-14 19:09:46.511979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891f71f857c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MemberData',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Level', sa.String(length=64), nullable=True),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('SmartPhone', sa.String(length=64), nullable=True),
    sa.Column('Time', sa.String(length=64), nullable=True),
    sa.Column('Description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MemberData')
    # ### end Alembic commands ###
